### ISSUE TITLE
bug: timestamp not change when kline fetch.

### ISSUE THREAD

**Issue by KageRyo** [KageRyo/Bybit-Predict#15]
# BybitAPI 改版至 v5.0
由於bybit的API改至v5.0有破壞性改動，
所以原先的版本直接死掉，
目前每次抓到的kline不會變
# 已完成
已完成以下變動：
- 依照[Bybit文件](https://bybit-exchange.github.io/docs/v5/market/kline)調整kline擷取方式。
- 原本時間戳是秒級，現在改成毫秒級。
# 未完成
輸出結果像這樣：
```json
{'retCode': 0, 'retMsg': 'OK', 'result': {'symbol': 'BTCUSDT', 'category': '', 'list': [['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532', '1241192933.652']]}, 'retExtInfo': {}, 'time': 1711639097748}
['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532']
1711610037800
{'retCode': 0, 'retMsg': 'OK', 'result': {'symbol': 'BTCUSDT', 'category': '', 'list': [['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532', '1241192933.652']]}, 'retExtInfo': {}, 'time': 1711639098355}
['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532']
1711610024400
{'retCode': 0, 'retMsg': 'OK', 'result': {'symbol': 'BTCUSDT', 'category': '', 'list': [['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532', '1241192933.652']]}, 'retExtInfo': {}, 'time': 1711639098833}
['1711612800000', '70467', '71084', '70352.5', '70733', '17548.532']
1711610011000
```
- 第一個是我在klineStatus裡面`print(kline_data)`
- 第二個是原本在saveData那邊`print(kline) #之前就有的`
- 第三個是我在klineStatus裡面`print(times)`
- 那確實發現times有在改變，可是似乎沒有被讀進去klineStatus的session.get中。
# 貢獻指南
請先於[pybit_api_v5](https://github.com/KageRyo/Bybit-Predict/tree/pybit_api_v5)分支中嘗試解決問題，若問題解決提交Pull Requests經review後沒問題我會再合併至此專案主分支。

**Comment by jason920612** [comment]
#17

**Comment by RRAaru** [comment]
已修復更新BybitAPI 5.0導致問題和其他程式錯誤
原BybitAPI 3.0時間戳為秒級以修正成BybitAPI 5.0的毫秒級
修正140行錯誤程式碼
修改datatime 3.12版後棄用的utcfromtimestamp()函式
