### ISSUE TITLE
變數命名錯誤

### ISSUE THREAD

**Issue by jason920612** [KageRyo/Bybit-Predict#2]
upK = []                 # 高於平均的多頭K線
downK = []               # 高於平均的空頭K線
變數名應該改成longK和shortK

**Comment by jason920612** [comment]
trendType 應該改成KlineType

**Comment by jason920612** [comment]
openPrice 應該改成open

**Comment by jason920612** [comment]
recommendedPosition 應該改成Recommended_Locations

**Comment by jason920612** [comment]
retracementText應該改成fibonacciTime

**Comment by jason920612** [comment]
fibonacciText應該改成fibonacci_Locations

**Comment by KageRyo** [comment]
thx for your sug, i will fix it.
